/************ ACTION Products TYPES **************/

export const PRODUCT_LIST_STARTED   = "PRODUCT_LIST_STARTED";
export const PRODUCT_LIST_FAILURE   = "PRODUCT_LIST_FAILURE";
export const PRODUCT_LIST_SUCCESS   = "PRODUCT_LIST_SUCCESS";

/*********** ACTION Category TYPES *****************/

export const CATEGORY_STARTED = "CATEGORY_STARTED";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CHANGE_CATEGORY  = "CHANGE_CATEGORY";

/************ ACTIONS DETAILS PRODUCT TYPES *********/

export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_STARTED = "PRODUCT_DETAILS_STARTED";
export const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE";

/********* ACTIONS CART *********************/
export const INIT_CART_STARTED  = "INIT_CART_STARTED";
export const INIT_CART_SUCCESS  = "INIT_CART_SUCCESS";
export const INIT_CART_FAILURE  = "INIT_CART_STARTED";
export const CART_ADD_ITEM      = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM   = "CART_REMOVE_ITEM";
export const CART_LIST_STARTED  = "CART_LIST_STARTED";
export const CART_LIST_SUCCESS  = "CART_LIST_SUCCESS";
export const CART_LIST_FAILURE  = "CART_LIST_FAILURE";
export const CLEAR_CART         = "CLEAR_CART";

/************* ACTIONS USER TYPES ***************/

export const USER_REGISTER_SUCCESS  = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_STARTED  = "USER_REGISTER_STARTED";
export const USER_REGISTER_FAILURE  = "USER_REGISTER_FAILURE";
export const CLEAR_ERROR_REGISTER   = "CLEAR_ERROR_REGISTER";

export const USER_LOGIN_SUCCESS     = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_STARTED     = "USER_LOGIN_STARTED";
export const USER_LOGIN_FAILURE     = "USER_LOGIN_FAILURE";
export const USER_LOGOUT            = "USER_LOGOUT";
export const CLEAR_ERROR_LOGIN      = "CLEAR_ERROR";

export const USER_PROFILE_STARTED   = "USER_PROFILE_STARTED";
export const USER_PROFILE_SUCCESS   = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE   = "USER_PROFILE_FAILURE";

export const UPDATE_USER_PROFILE    = "UPDATE_USER_PROFILE";

export const USER_UPDATE_DB_STARTED = "USER_UPDATE_STARTED";
export const USER_UPDATE_DB_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_DB_FAILURE = "USER_UPDATE_FAILURE";

export const CLEAR_STATUS_CODE = "CLEAR_STATUS_CODE";
/*************** ACTIONS PAYMENT ************/
export const PAYMENT_LIST_STARTED   = "PAYMENT_LIST_STARTED";
export const PAYMENT_LIST_FAILURE   = "PAYMENT_LIST_FAILURE";
export const PAYMENT_LIST_SUCCESS   = "PAYMENT_LIST_SUCCESS";
export const SAVE_PAYMENT           = "SAVE_PAYMENT";

/*************** ACTIONS DELIVERY ************/
export const DELIVERY_LIST_STARTED   = "DELIVERY_LIST_STARTED";
export const DELIVERY_LIST_FAILURE   = "DELIVERY_LIST_FAILURE";
export const DELIVERY_LIST_SUCCESS   = "DELIVERY_LIST_SUCCESS";
export const SAVE_DELIVERY           = "SAVE_DELIVERY";

/*************** ACTIONS ORDER ************/

export const ADD_ORDER          = "ADD_ORDER";
export const ORDER_LIST_STARTED = "ORDER_LIST_STARTED";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILURE = "ORDER_LIST_FAILURE";

export const ORDER_DETAILS_STARTED = "ORDER_DETAILS_STARTED";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILURE = "ORDER_DETAILS_FAILURE";


